apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: django-messaging-green   # Switch to green when ready
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
